### ISSUE TITLE
handle target specific dependencies

### ISSUE THREAD

**Issue by ToBinio** [ToBinio/cargo-features-manager#18]
e.g. 

```toml
[target.'cfg(unix)'.dependencies]
fork = "0.1"
```
